name: Test Cache
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3.6.0
      - uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c  # v3.5.0
        with:
          path: ~/.npm
          key: test-cache-key
      - run: echo "Testing cache"