name: Test Multiple Actions
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # v3.6.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610  # v3.9.1
        with:
          node-version: '18'
      - uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c  # v3.5.0
        with:
          path: node_modules
          key: test-${{ hashFiles('**/package-lock.json') }}
      - run: echo "Multiple actions test"